spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&verifyServerCertificate=false&allowMultiQueries=true&serverTimezone=Hongkong
    username: root
    password: xxx
  servlet:
    multipart:
      max-file-size: 10MB
  task:
    execution:
      pool:
        core-size: 50
        max-size: 500
        queue-capacity: 1500
      thread-name-prefix: ExcelAsync-
      shutdown:
        await-termination: true
        await-termination-period: 900S
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: ai.guiji.easyexcel.examples.entity
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

