spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&verifyServerCertificate=false&allowMultiQueries=true&serverTimezone=Hongkong
    username: root
    password: xxx
  servlet:
    multipart:
      max-file-size: 10MB
  task:
    execution:
      pool:
        core-size: 50
        max-size: 500
        queue-capacity: 1500
      thread-name-prefix: ExcelAsync-
      shutdown:
        await-termination: true
        await-termination-period: 900S
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 172.16.2.107 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: xxx # Redis服务器连接密码（默认为空）
    timeout: 5000 # 连接超时时间（毫秒）
    redisson:
      config: classpath:redisson-single.yml
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: ai.guiji.easyexcel.examples.entity
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

